=== rahn9/parsers_task/src/main/webapp/xml/internet-shop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="shop" type="shop-type"/>

    <xs:complexType name="shop-type">
        <xs:sequence>
            <xs:element name="category" type="category-type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="category-type">
        <xs:sequence>
            <xs:element name="subcategory" type="subcategory-type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>

    <xs:complexType name="subcategory-type">
        <xs:sequence>
            <xs:element name="product" type="product-type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>

    <xs:complexType name="product-type">
        <xs:sequence>
            <xs:element name="product-name" type="xs:string"/>
            <xs:element name="producer" type="xs:string"/>
            <xs:element name="model">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-z]{2}\d{3}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="date-of-issue" type="date-type"/>
            <xs:element name="color" type="xs:string"/>
            <xs:choice>
                <xs:element name="price">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:minInclusive value="0.0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element type="xs:boolean" name="not_in_stock" fixed="true"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute type="UUID-type" name="id" use="required"/>
    </xs:complexType>

    <xs:simpleType name="UUID-type">
        <xs:restriction base="xs:ID">
            <xs:pattern
                    value="[\w]{8}-[\w]{4}-[\w]{4}-[\w]{4}-[\w]{12}">
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="date-type">
        <xs:restriction base="xs:string">
            <xs:pattern
                    value="(0?[1-9]|[12][0-9]|3[01])-(0?[1-9]|1[012])-((19|20)\d\d)">
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== rahn9/parsers_task/src/main/resources/internet-shop.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE shop SYSTEM "internet-shop.dtd">
<shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="internet-shop.xsd">
    <category>
        <name>Mobile devices</name>
        <subcategory>
            <name>Smartphone</name>
            <product>
                <id>a234asdf-a2as-a2as-a2as-a234asdf1234</id>
                <name>Asus Zenfone 2 Laser</name>
                <producer>ASUS</producer>
                <model>Sd123</model>
                <date-of-issue>11-11-2015</date-of-issue>
                <color>red</color>
                <price>56.66</price>
            </product>
            <product>
                <id>s23e4567-e89b-g2d3-a456-ff6655440000</id>
                <name>Asus Zenfone 2 Laser</name>
                <producer>Asus</producer>
                <model>aa123</model>
                <date-of-issue>12-11-2015</date-of-issue>
                <color>black</color>
                <not_in_stock>true</not_in_stock>
            </product>
            <product>
                <id>s11e4567-e89b-g2d3-a456-f12255440000</id>
                <name>Asus Zenfone 2 Laser</name>
                <producer>Asus</producer>
                <model>DC678</model>
                <date-of-issue>17-11-2015</date-of-issue>
                <color>blue</color>
                <price>56.88</price>
            </product>
        </subcategory>
        <subcategory>
            <name>Tablets</name>
            <product>
                <id>f1234123-f123-f123-f123-ffff12341234</id>
                <name>Ipad air</name>
                <producer>Apple</producer>
                <model>ss234</model>
                <date-of-issue>01-11-2015</date-of-issue>
                <color>black</color>
                <price>500</price>
            </product>
            <product>
                <id>a1234123-a123-a123-a123-aaaa12341234</id>
                <name>Ipad 4</name>
                <producer>Apple</producer>
                <model>dd124</model>
                <date-of-issue>03-11-2015</date-of-issue>
                <color>white</color>
                <price>300</price>
            </product>
            <product>
                <id>b1231234-b123-b123-b123-bbbb12341234</id>
                <name>ThinkPad Tablet</name>
                <producer>Lenovo</producer>
                <model>gg644</model>
                <date-of-issue>23-11-2015</date-of-issue>
                <color>black</color>
                <not_in_stock>true</not_in_stock>
            </product>
        </subcategory>
    </category>
</shop>

=== rahn9/parsers_task/src/main/webapp/xml/internet-shop.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE shop SYSTEM "C:\Users\Vakhidat_Matiyeva@epam.com\IdeaProjects\parser\src\main\webapp\xml\internet-shop.dtd">
<shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="internet-shop.xsd">
    <category name="Mobile devices">
        <subcategory name="Smartphone">
            <product id="b215f9e4-804b-408b-a0b6-5de01b80b4eb">
                <product-name>Asus Zenfone 2 Laser</product-name>
                <producer>ASUS</producer>
                <model>Sd123</model>
                <date-of-issue>11-11-2015</date-of-issue>
                <color>red</color>
                <price>56.66</price>
            </product>
            <product id="d12e63ff-b14a-4fb9-811f-3de4f4c48576">
                <product-name>Asus Zenfone 2 Laser</product-name>
                <producer>Asus</producer>
                <model>aa123</model>
                <date-of-issue>12-11-2015</date-of-issue>
                <color>black</color>
                <not_in_stock>true</not_in_stock>
            </product>
            <product id="b1fbc22e-5833-4cd6-a4fe-f127265f31ad">
                <product-name>Asus Zenfone 2 Laser</product-name>
                <producer>Asus</producer>
                <model>DC678</model>
                <date-of-issue>17-11-2015</date-of-issue>
                <color>blue</color>
                <price>56.88</price>
            </product>
        </subcategory>
        <subcategory name="Tablets">
            <product id="c56c28a2-c122-4337-b24f-4cd60cb932be">
                <product-name>Ipad air</product-name>
                <producer>Apple</producer>
                <model>ss234</model>
                <date-of-issue>01-11-2015</date-of-issue>
                <color>black</color>
                <price>500</price>
            </product>
            <product id="ad57cf47-8882-496c-a298-8004f2a255c7">
                <product-name>Ipad 4</product-name>
                <producer>Apple</producer>
                <model>dd124</model>
                <date-of-issue>03-11-2015</date-of-issue>
                <color>white</color>
                <price>300</price>
            </product>
            <product id="b0eec2cd-fee2-4b5a-afe6-53f219bba14e">
                <product-name>ThinkPad Tablet</product-name>
                <producer>Lenovo</producer>
                <model>gg644</model>
                <date-of-issue>23-11-2015</date-of-issue>
                <color>black</color>
                <not_in_stock>true</not_in_stock>
            </product>
        </subcategory>
    </category>
</shop>
